# Generated by Django 4.1.3 on 2022-12-01 17:30

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_related_page_home'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='currentSituation',
        ),
        migrations.RemoveField(
            model_name='home',
            name='leftLogo',
        ),
        migrations.RemoveField(
            model_name='home',
            name='rightLogo',
        ),
        migrations.AlterField(
            model_name='home',
            name='line1',
            field=wagtail.fields.RichTextField(blank=True, null=True, verbose_name='Текущее положение дел'),
        ),
        migrations.AlterField(
            model_name='home',
            name='line2',
            field=wagtail.fields.RichTextField(blank=True, null=True, verbose_name='Текущее положение дел'),
        ),
        migrations.AlterField(
            model_name='home',
            name='line3',
            field=wagtail.fields.RichTextField(blank=True, null=True, verbose_name='Текущее положение дел'),
        ),
        migrations.AlterField(
            model_name='home',
            name='line4',
            field=wagtail.fields.RichTextField(blank=True, null=True, verbose_name='Текущее положение дел'),
        ),
        migrations.AlterField(
            model_name='home',
            name='line5',
            field=wagtail.fields.RichTextField(blank=True, null=True, verbose_name='Текущее положение дел'),
        ),
        migrations.AlterField(
            model_name='home',
            name='line6',
            field=wagtail.fields.RichTextField(blank=True, null=True, verbose_name='Текущее положение дел'),
        ),
    ]
