# Generated by Django 4.1.3 on 2022-12-01 18:03

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_home_currentsituation_remove_home_leftlogo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='line1',
            field=wagtail.fields.RichTextField(blank=True, null=True, verbose_name='Первый столбец, первая строка'),
        ),
        migrations.AlterField(
            model_name='home',
            name='line2',
            field=wagtail.fields.RichTextField(blank=True, null=True, verbose_name='Первый столбец, вторая строка'),
        ),
        migrations.AlterField(
            model_name='home',
            name='line3',
            field=wagtail.fields.RichTextField(blank=True, null=True, verbose_name='Второй столбец, третья строка'),
        ),
        migrations.AlterField(
            model_name='home',
            name='line4',
            field=wagtail.fields.RichTextField(blank=True, null=True, verbose_name='Второй столбец, третья строка'),
        ),
        migrations.AlterField(
            model_name='home',
            name='line5',
            field=wagtail.fields.RichTextField(blank=True, null=True, verbose_name='Третий столбец, первая строка'),
        ),
        migrations.AlterField(
            model_name='home',
            name='line6',
            field=wagtail.fields.RichTextField(blank=True, null=True, verbose_name='Третий столбец, вторая строка'),
        ),
    ]
