# Generated by Django 4.1.3 on 2022-12-01 18:12

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_home_line1_alter_home_line2_alter_home_line3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='line1',
        ),
        migrations.RemoveField(
            model_name='home',
            name='line2',
        ),
        migrations.RemoveField(
            model_name='home',
            name='line3',
        ),
        migrations.RemoveField(
            model_name='home',
            name='line4',
        ),
        migrations.RemoveField(
            model_name='home',
            name='line5',
        ),
        migrations.RemoveField(
            model_name='home',
            name='line6',
        ),
        migrations.AddField(
            model_name='home',
            name='r1',
            field=wagtail.fields.RichTextField(blank=True, null=True, verbose_name='Первый столбец, первая строка'),
        ),
        migrations.AddField(
            model_name='home',
            name='r2',
            field=wagtail.fields.RichTextField(blank=True, null=True, verbose_name='Первый столбец, вторая строка'),
        ),
        migrations.AddField(
            model_name='home',
            name='r3',
            field=wagtail.fields.RichTextField(blank=True, null=True, verbose_name='Второй столбец, третья строка'),
        ),
        migrations.AddField(
            model_name='home',
            name='r4',
            field=wagtail.fields.RichTextField(blank=True, null=True, verbose_name='Второй столбец, третья строка'),
        ),
        migrations.AddField(
            model_name='home',
            name='r5',
            field=wagtail.fields.RichTextField(blank=True, null=True, verbose_name='Третий столбец, первая строка'),
        ),
        migrations.AddField(
            model_name='home',
            name='r6',
            field=wagtail.fields.RichTextField(blank=True, null=True, verbose_name='Третий столбец, вторая строка'),
        ),
    ]
