# Generated by Django 4.1.3 on 2022-12-01 18:25

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_home_line1_remove_home_line2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='r1',
            field=wagtail.fields.RichTextField(blank=True, null=True, verbose_name='Первый столбец, первая строка'),
        ),
    ]
