# Generated by Django 4.1.3 on 2022-12-01 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_homepage_r1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='r1',
            new_name='rt1',
        ),
    ]
