# Generated by Django 4.1.3 on 2022-12-01 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_rename_r1_homepage_rt1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='rt1',
        ),
    ]
