# Generated by Django 4.1.3 on 2022-12-20 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0002_krtnews_file_id_alter_krtnews_message_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KrtNews',
        ),
    ]
