# Generated by Django 4.1.3 on 2022-12-20 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KrtNews',
            fields=[
                ('messageId', models.PositiveSmallIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Message id from the channel')),
                ('message_date', models.DateTimeField(verbose_name='Message date from the channel')),
                ('message', models.CharField(max_length=100, verbose_name='Message from channel')),
                ('file_id', models.CharField(max_length=100, null=True, verbose_name='attached image id in telegram api')),
                ('full_message', models.JSONField(verbose_name='Full message from the channel')),
            ],
            options={
                'verbose_name_plural': 'KrtNews',
            },
        ),
    ]
