# Generated by Django 4.1.3 on 2022-12-24 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krtnews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='krtnews',
            name='message',
            field=models.CharField(max_length=150, verbose_name='Message from channel'),
        ),
    ]
